PYIC-3201 Create CIMIT stub lambda dynamo db table
govuk-one-login/ipv-stubs pull request #415
Opened 2023-07-19 08:47 UTC by TalatAydinGDS

## Proposed changes

### What changed

Create CIMIT stub lambda dynamo db table

### Why did it change

This stores CI and mitigation data for a given user id

### Issue tracking

- [PYI-3201](https://govukverify.atlassian.net/browse/PYI-3201)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-07-19 09:14 UTC, therealslimsladey requested changes

2023-07-19 09:14 UTC, therealslimsladey commented on di-ipv-cimit-stub/deploy/template.yaml
> +      KeySchema:
The primary key is a composite key of `userId` and `contraIndicatorCode` with the userId being the partition (HASH) key and the contraIndicatorCode being the sort (RANGE) key, akin to the user-credentials-v2 and cri-response tables in core-back. No need for secondary indexes methinks.

So
```
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
        - AttributeName: "contraIndicatorCode"
          KeyType: "RANGE"
```

2023-07-19 09:14 UTC, therealslimsladey commented on di-ipv-cimit-stub/deploy/template.yaml
> +      GlobalSecondaryIndexes:
As above, I don't think we need this.

2023-07-19 09:14 UTC, therealslimsladey commented on di-ipv-cimit-stub/lib/build.gradle
> +sourceCompatibility = 17
we should be specifying both source and target compatibility and I think we're dropping to 11?

2023-07-19 09:14 UTC, therealslimsladey commented on di-ipv-cimit-stub/lib/src/main/java/uk/gov/di/ipv/core/library/persistence/DataStore.java
Are we really going to use the local running facility and all the methods that are present? Let's tidy this up once we know which methods we're going to be using in the management API

2023-07-19 09:14 UTC, therealslimsladey commented on di-ipv-cimit-stub/lib/src/main/java/uk/gov/di/ipv/core/library/persistence/items/CimitStubItem.java
> +    @DynamoDbSecondaryPartitionKey(indexNames = "contraIndicatorCode")
This is going to be the DynamoDbSortKey

2023-07-19 09:27 UTC, TalatAydinGDS commented on di-ipv-cimit-stub/deploy/template.yaml
> +      KeySchema:
Done

2023-07-19 09:27 UTC, TalatAydinGDS commented on di-ipv-cimit-stub/deploy/template.yaml
> +      GlobalSecondaryIndexes:
Done

2023-07-19 09:27 UTC, TalatAydinGDS commented on di-ipv-cimit-stub/lib/build.gradle
> +sourceCompatibility = 17
Done

2023-07-19 09:27 UTC, TalatAydinGDS commented on di-ipv-cimit-stub/lib/src/main/java/uk/gov/di/ipv/core/library/persistence/items/CimitStubItem.java
> +    @DynamoDbSecondaryPartitionKey(indexNames = "contraIndicatorCode")
Done

2023-07-20 07:34 UTC, therealslimsladey approved these changes
lgtm

2023-07-20 08:02 UTC, merged