PYIC 3329 Switch newly created Cimit stub to Java 17
govuk-one-login/ipv-stubs pull request #445
Opened 2023-08-04 11:15 UTC by rpayal

## Proposed changes
Switch newly created Cimit stub (all lambdas) to Java 17

### What changed
- Changes made to switch cimit-stub module to Java17
- Changes made to stub modules to bump gradle-8.2.1.

### Why did it change

### Issue tracking

- [PYI-3329](https://govukverify.atlassian.net/browse/PYI-3329)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-08-07 10:12 UTC, therealslimsladey requested changes

2023-08-07 10:12 UTC, therealslimsladey commented on di-ipv-cimit-stub/lambdas/get-contra-indicator-credential/build.gradle
> +	aspect('org.aspectj:aspectjrt') {
What's the reason for introducing this?

2023-08-07 10:12 UTC, therealslimsladey commented on di-ipv-cimit-stub/lambdas/get-contra-indicator-credential/build.gradle
> +	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
What's the reason for introducing this?

2023-08-07 10:12 UTC, therealslimsladey commented on di-ipv-credential-issuer-stub/build.gradle
> +	sourceCompatibility = JavaVersion.VERSION_17
Specify targetCompatibility as well to avoid doubt.

2023-08-07 10:12 UTC, therealslimsladey commented on di-ipv-core-stub/build.gradle
> +	sourceCompatibility = JavaVersion.VERSION_17
And targetCompatibility

2023-08-07 10:12 UTC, therealslimsladey commented on di-ipv-orchestrator-stub/build.gradle
> +	sourceCompatibility = JavaVersion.VERSION_17
and targetCompatibility

2023-08-07 10:36 UTC, rpayal commented on di-ipv-credential-issuer-stub/build.gradle
> +	sourceCompatibility = JavaVersion.VERSION_17
By default, if not specified, targetCompatibility=sourceCompatibility.

2023-08-07 10:40 UTC, rpayal commented on di-ipv-cimit-stub/lambdas/get-contra-indicator-credential/build.gradle
> +	aspect('org.aspectj:aspectjrt') {
To override the transient dependency, explained in the ticket comment.

Resolve transitive dependency issue for aspectjrtfrom software.amazon.lambda:powertools-logging and software.amazon.lambda:powertools-tracing to resolve following issue during build
> Task :di-ipv-cimit-stub:lambdas:get-contra-indicators:compileJava FAILED
[error] target level should be in '1.1'...'1.8','9'...'16' (or '5.0'..'16.0') or cldc1.1: 17
org.aspectj:aspectjrt to version 1.9.8

2023-08-07 10:51 UTC, rpayal commented on di-ipv-cimit-stub/lambdas/get-contra-indicator-credential/build.gradle
> +	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
Added testRuntimeOnly("org.junit.platform:junit-platform-launcher") in build.gradle to remove the following deprecation warning;

Task :di-ipv-cimit-stub:lambdas:get-contra-indicator-credential:test
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: [Upgrading your build from Gradle 8.x to the latest](https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#test_framework_implementation_dependencies)

2023-08-07 11:14 UTC, TalatAydinGDS requested changes
These changes looks good for me. but I think, don't need to repeat the common configurations in each lambda projects 'build.gradle' file. We can add hierarchy in the root 'build.gradle' file to avoid duplicating the similar configuration for all lambdas projects. By doing this, we can make changes in one places and have those changes reflected in all lambda projects. So, this hierarchy will help we centralize the configurations and make it easier to manage and maintain our Gradle project and can see only different dependencies and configurations in lambda's build.gradle. We can do it in this task or different task?

2023-08-09 13:55 UTC, TobySaundersGDS approved these changes

2023-08-09 15:02 UTC, therealslimsladey approved these changes

2023-08-09 15:04 UTC, TalatAydinGDS approved these changes
LGTM

2023-08-09 15:15 UTC, merged