PYIC 4188: call to stub management handler lambda for add issuer to t…
govuk-one-login/ipv-stubs pull request #587
Opened 2023-12-14 16:40 UTC by TalatAydinGDS

## Proposed changes

### What changed

If Any ContraIndicator(CI) is set within any CRI stub, invoke to the POST CIS operation in Cimit Stub's Stub Management. This way, we store the 'issuers' within the CimitStubItem   

### Why did it change

So, can add issuers within the response from  GetContraIndicatorCredential CimitStub's lambda, similar to how it is done in the SPOT CIMIT's response 

### Issue tracking

- [PYIC-4188](https://govukverify.atlassian.net/browse/PYIC-4188)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-12-14 17:34 UTC, Joe-Edwards-GDS requested changes
I don't think we need any changes in `AuthorizeHandler` - it should all be handled by the CI storage logic.

Does anything actually use the PUT CimitStubItem management API at the moment?

2023-12-14 17:34 UTC, Joe-Edwards-GDS commented on di-ipv-cimit-stub/lambdas/put-contra-indicators/src/main/java/uk/gov/di/ipv/core/putcontraindicators/service/ContraIndicatorsService.java
>                      } else {
Do we need to update the `else` branch here to combine the issuers from `cimitStubItem` and `dbCimitStubItem` (like in the management API)?

2023-12-14 17:34 UTC, Joe-Edwards-GDS commented on di-ipv-cimit-stub/lambdas/stub-management/src/main/java/uk/gov/di/ipv/core/stubmanagement/service/UserService.java
> +    private List<String> getUpdatedList(
Maybe `mergeStringLists` would be a better description of what it's doing?

2023-12-14 17:34 UTC, Joe-Edwards-GDS commented on di-ipv-cimit-stub/lambdas/stub-management/src/main/java/uk/gov/di/ipv/core/stubmanagement/service/UserService.java
> +                : combinedStream.distinct().collect(Collectors.toList());
I think you can just call `.toList()` here (assuming we're using Java 16+)

2023-12-14 17:34 UTC, Joe-Edwards-GDS commented on di-ipv-cimit-stub/lambdas/put-contra-indicators/src/main/java/uk/gov/di/ipv/core/putcontraindicators/service/ContraIndicatorsService.java
> +                                cimitStubItem.getIssuers(),
Do we need to update `mapToContraIndications` to set this? Otherwise I think it'll always be null...

2023-12-14 17:34 UTC, Joe-Edwards-GDS commented on di-ipv-credential-issuer-stub/src/main/java/uk/gov/di/ipv/stub/cred/handlers/AuthorizeHandler.java
> +                                            .getClaim(RequestParamConstants.ISSUER)
Can you just call `.getIssuer()` here?

2023-12-14 17:34 UTC, Joe-Edwards-GDS commented on di-ipv-credential-issuer-stub/src/main/java/uk/gov/di/ipv/stub/cred/handlers/AuthorizeHandler.java
> +                        if (!ciString.isEmpty()) {
We've already checked that `ciString` is nonempty in the outer condition

2023-12-14 17:34 UTC, Joe-Edwards-GDS commented on di-ipv-credential-issuer-stub/src/main/java/uk/gov/di/ipv/stub/cred/handlers/AuthorizeHandler.java
> +                            processIssuersCIs(
I'm a bit confused about this - are you adding an extra call to the stub management API that wasn't here before?

I don't think you need to do this - we should be setting the CIs/Issuers when IPV Core submits the VC to the CIMIT stub (i.e. in `ContraIndicatorsService`). I think this change will result in duplicate CIs being recorded?

2023-12-15 15:55 UTC, TalatAydinGDS commented
changed approach and can close this PR

2023-12-15 15:55 UTC, closed without merging