PYIC-4933: Added experian-kbv-stub workflow and deployment template
govuk-one-login/ipv-stubs pull request #679
Opened 2024-03-05 15:17 UTC by RogVanGDS

## Proposed changes

### What changed

Added experian-kbv-stub workflow and deployment template

### Why did it change

This allows us to deploy a new experian-kbv-stub stack, as the first part of the process of renaming kbv-stub to experian-kbv-stub.

### Issue tracking

- [PYI-4933](https://govukverify.atlassian.net/browse/PYI-4933)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2024-03-07 10:12 UTC, DanCorderIPV approved these changes
I'm going to assume the these files are basically copies of the existing ones with `experian` added :)
I do think we need another PR for this phase of the work to set up the necessary config for this CRI stub in parallel with the existing stub.

2024-03-07 10:12 UTC, DanCorderIPV commented on .github/workflows/cri-experian-kbv-stub.yml
> +          role-to-assume: ${{ secrets.CRI_EXPERIAN_KBV_GH_ACTIONS_ROLE_ARN }}
Has this secret been created?

2024-03-07 10:12 UTC, DanCorderIPV commented on .github/workflows/cri-experian-kbv-stub.yml
> +          ECR_REPOSITORY: ${{ secrets.CRI_EXPERIAN_KBV_ECR_REPOSITORY }}
new secret

2024-03-07 10:12 UTC, DanCorderIPV commented on .github/workflows/cri-experian-kbv-stub.yml
> +          ARTIFACT_BUCKET: ${{ secrets.CRI_EXPERIAN_KBV_ARTIFACT_BUCKET_NAME }}
new secret

2024-03-07 10:12 UTC, DanCorderIPV commented on di-ipv-credential-issuer-stub/deploy/experian-kbv/template.yaml
> +    Default: "/stubs/credential-issuer/experian-kbv/env/JBP_CONFIG_OPEN_JDK_JRE" #pragma: allowlist secret
There doesn't seem to be any config in AWS for `experian-kbv`
I see that there is a separate PR to swap the config names, but I think we should actually duplicate the config so that we can test this new instance of the CRI before we switch everyone over to it.

2024-03-07 10:28 UTC, DanCorderIPV commented on di-ipv-credential-issuer-stub/deploy/experian-kbv/template.yaml
> +    Default: "/stubs/credential-issuer/experian-kbv/env/JBP_CONFIG_OPEN_JDK_JRE" #pragma: allowlist secret
Actually, I think this probably needs to stay as `credential-issuer/kbv` and PYIC-4394 will rename it later on.
Your other PR to update the config doesn't change the key names, just the values

2024-03-07 10:28 UTC, DanCorderIPV requested changes, later dismissed
The SSM key names shouldn't change

2024-03-07 10:42 UTC, RogVanGDS commented on .github/workflows/cri-experian-kbv-stub.yml
> +          role-to-assume: ${{ secrets.CRI_EXPERIAN_KBV_GH_ACTIONS_ROLE_ARN }}
Yep, Vam has added them

2024-03-07 10:42 UTC, RogVanGDS commented on .github/workflows/cri-experian-kbv-stub.yml
> +          ECR_REPOSITORY: ${{ secrets.CRI_EXPERIAN_KBV_ECR_REPOSITORY }}
Added by Vam

2024-03-07 10:42 UTC, RogVanGDS commented on .github/workflows/cri-experian-kbv-stub.yml
> +          ARTIFACT_BUCKET: ${{ secrets.CRI_EXPERIAN_KBV_ARTIFACT_BUCKET_NAME }}
Added by Vam

2024-03-07 10:47 UTC, RogVanGDS commented on di-ipv-credential-issuer-stub/deploy/experian-kbv/template.yaml
> +    Default: "/stubs/credential-issuer/experian-kbv/env/JBP_CONFIG_OPEN_JDK_JRE" #pragma: allowlist secret
PYIC-4394 -> What is this sorry?

2024-03-07 11:02 UTC, vam-gds approved these changes, later dismissed

2024-03-07 16:53 UTC, DanCorderIPV commented on di-ipv-credential-issuer-stub/deploy/experian-kbv/template.yaml
> +    Default: "/stubs/credential-issuer/experian-kbv/env/JBP_CONFIG_OPEN_JDK_JRE" #pragma: allowlist secret
Changing the CRI ID from `kbv` IIRC the ID is what is used to extract config and what is used in the redirect URI

2024-03-08 14:19 UTC, RogVanGDS commented on di-ipv-credential-issuer-stub/deploy/experian-kbv/template.yaml
> +    Default: "/stubs/credential-issuer/experian-kbv/env/JBP_CONFIG_OPEN_JDK_JRE" #pragma: allowlist secret
Did you get the wrong ticket number? That one is for a VC reset

2024-03-12 10:23 UTC, vam-gds commented
:+1:  looks good been working with Roger deploying to dev env - its all deployed in dev now as well which should be good.

2024-03-12 10:24 UTC, vam-gds approved these changes

2024-03-12 10:25 UTC, merged